"use client"; // This is a client component 👈🏽

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/l1ruO4J2a0x
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Link from "next/link";
import { Button } from "@/components/ui/button";
import React, { useState } from "react";

export function HomepageComponent() {
  const [image, setImage] = useState(null);

  const handleImageChange = (e: any) => {
    const file = e.target.files[0];
    const reader = new FileReader();

    reader.onloadend = () => {
      // @ts-ignore
      setImage(reader.result);
    };

    if (file) {
      reader.readAsDataURL(file);
    }
  };

  return (
    <div className="flex flex-col h-screen">
      <header className="flex items-center justify-center py-4 border-b border-gray-100 dark:border-gray-800">
        <div className="container flex items-center gap-4 px-4 md:px-6">
          <Link
            className="flex items-center gap-2 text-xl font-semibold"
            href="#"
          >
            <FlagIcon className="w-6 h-6" />
            v0
          </Link>
          <nav className="ml-auto space-x-4">
            <Link
              className="flex items-center space-x-2 text-sm font-medium"
              href="#"
            >
              <HomeIcon className="w-4 h-4" />
              Home
            </Link>
            <Link
              className="flex items-center space-x-2 text-sm font-medium"
              href="#"
            >
              <BookIcon className="w-4 h-4" />
              Docs
            </Link>
            <Link
              className="flex items-center space-x-2 text-sm font-medium"
              href="#"
            >
              <PackageIcon className="w-4 h-4" />
              Components
            </Link>
            <Link
              className="flex items-center space-x-2 text-sm font-medium"
              href="#"
            >
              <TerminalIcon className="w-4 h-4" />
              CLI
            </Link>
            <Link
              className="flex items-center space-x-2 text-sm font-medium"
              href="#"
            >
              <GithubIcon className="w-4 h-4" />
              GitHub
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex flex-1 items-center justify-center">
        <div className="container flex flex-1 flex-col items-center gap-4 px-4 md:px-6">
          <div className="w-full max-w-lg space-y-4">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
              Customize your instance
            </h1>
            <p className="text-gray-500 md:text-xl dark:text-gray-400">
              Upload your logo and configure your instance to match your brand.
            </p>
            <div className="border border-dashed border-gray-200 rounded-lg w-full h-[200px] flex items-center justify-center">
              <input
                accept="image/*"
                onChange={handleImageChange}
                className="absolute inset-0 overflow-hidden opacity-0 w-full h-full cursor-pointer z-10"
                type="file"
              />
              <div className="text-center space-y-2">
                <ImageIcon className="w-12 h-12 mx-auto" />
                <div className="text-sm font-medium text-gray-500 dark:text-gray-400">
                  Drag and drop your image here or click to browse
                </div>
              </div>
            </div>
            <Button className="w-full" onClick={undefined}>
              Open Camera
            </Button>
            <div>
              {image && (
                <img
                  src={image}
                  alt="Uploaded"
                  style={{ maxWidth: "100%", marginTop: "10px" }}
                />
              )}
            </div>
          </div>
        </div>
      </main>
      <footer className="flex items-center justify-center py-4 border-t border-gray-100 dark:border-gray-800">
        <div className="container flex items-center gap-4 px-4 md:px-6">
          <div className="text-sm text-gray-500 dark:text-gray-400">
            © 2022 Vercel - Your Company -
            <Link className="underline underline-offset-2" href="#">
              Privacy Policy
            </Link>
          </div>
          <div className="ml-auto grid gap-2 sm:gap-4 grid-flow-col auto-cols-auto">
            <Link className="text-sm font-medium" href="#">
              Support
            </Link>
            <Link className="text-sm font-medium" href="#">
              Contact Us
            </Link>
            <Link className="text-sm font-medium" href="#">
              Terms
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  );
}

function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  );
}

function GithubIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  );
}

function ImageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <circle cx="9" cy="9" r="2" />
      <path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21" />
    </svg>
  );
}

function PackageIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m7.5 4.27 9 5.15" />
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  );
}

function TerminalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 17 10 11 4 5" />
      <line x1="12" x2="20" y1="19" y2="19" />
    </svg>
  );
}
