/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/SFQBWWlmqaW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Syne } from 'next/font/google'
import { Comfortaa } from 'next/font/google'

syne({
  subsets: ['latin'],
  display: 'swap',
})

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function SpotifySuggestions() {
  return (
    <div className="flex flex-col h-screen w-full">
      <header className="flex items-center h-14 px-4 border-b sm:h-16 lg:px-6">
        <div className="flex items-center gap-2">
          <MusicIcon className="h-6 w-6 text-spotify" />
          <span className="text-lg font-semibold">Spotify</span>
        </div>
        <nav className="ml-auto flex items-center gap-4 lg:gap-6">
          <div className="flex items-center gap-0.5">
            <SearchIcon className="w-4 h-4" />
            <Input className="w-20 h-6 text-xs rounded-md border-0 shadow-none" placeholder="Search" type="search" />
          </div>
          <Button className="h-8 text-xs" variant="outline">
            Upgrade
          </Button>
          <div>
            <div className="flex items-center gap-2">
              <img
                alt="Avatar"
                className="rounded-full object-cover"
                height="24"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "24/24",
                  objectFit: "cover",
                }}
                width="24"
              />
              <span className="text-xs font-semibold">User</span>
              <ChevronDownIcon className="w-4 h-4" />
            </div>
            <div className="min-w-[180px]">
              <div>
                <a className="block px-2 py-1 text-sm rounded-md" href="#">
                  Logout
                </a>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main className="flex-1 overflow-auto p-4 md:p-6">
        <div className="container mx-auto grid gap-4 grid-cols-2 text-center">
          <div>
            <h1 className="text-2xl font-bold">Upload your image</h1>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <img
                alt="Uploaded image"
                className="rounded-lg object-cover border border-gray-200 w-full aspect-square overflow-hidden dark:border-gray-800 dark:border-gray-800"
                height="400"
                src="/placeholder.svg"
                width="400"
              />
              <Button className="w-full">Upload a new image</Button>
              <Button className="w-full" variant="outline">
                Delete image
              </Button>
            </div>
          </div>
          <div>
            <h1 className="text-2xl font-bold">Spotify Songs</h1>
            <ul className="text-left">
              <li className="flex items-center justify-between cursor-pointer text-blue-500 hover:underline">
                <span>Song 1</span>
                <Button className="h-6 w-6" variant="icon">
                  <PlayIcon className="h-4 w-4" />
                </Button>
              </li>
              <li className="flex items-center justify-between cursor-pointer text-blue-500 hover:underline">
                <span>Song 2</span>
                <Button className="h-6 w-6" variant="icon">
                  <PlayIcon className="h-4 w-4" />
                </Button>
              </li>
              <li className="flex items-center justify-between cursor-pointer text-blue-500 hover:underline">
                <span>Song 3</span>
                <Button className="h-6 w-6" variant="icon">
                  <PlayIcon className="h-4 w-4" />
                </Button>
              </li>
              <li className="flex items-center justify-between cursor-pointer text-blue-500 hover:underline">
                <span>Song 4</span>
                <Button className="h-6 w-6" variant="icon">
                  <PlayIcon className="h-4 w-4" />
                </Button>
              </li>
              <li className="flex items-center justify-between cursor-pointer text-blue-500 hover:underline">
                <span>Song 5</span>
                <Button className="h-6 w-6" variant="icon">
                  <PlayIcon className="h-4 w-4" />
                </Button>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function MusicIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 18V5l12-2v13" />
      <circle cx="6" cy="18" r="3" />
      <circle cx="18" cy="16" r="3" />
    </svg>
  )
}


function PlayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="5 3 19 12 5 21 5 3" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
