/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pF2nd0hqWpy
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { DM_Sans } from 'next/font/google'
import { Manrope } from 'next/font/google'

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

manrope({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";

export function SpotifySuggestions2() {
  return (
    <div className="flex flex-col h-screen">
      <header className="flex items-center h-14 px-4 border-b gap-2 sm:gap-4 text-sm font-semibold dark:border-gray-800">
        <div className="flex items-center gap-2">
          <MusicIcon className="w-6 h-6 fill-gray-900 dark:fill-gray-50" />
          Spotify Suggestions
        </div>
        <div className="ml-auto flex items-center gap-4 md:gap-2">
          <Button className="hidden md:flex" size="sm" variant="outline">
            <UploadIcon className="w-4 h-4 mr-2" />
            Upload Image
          </Button>
          <Button
            className="md:hidden flex-1 justify-center"
            size="sm"
            variant="outline"
          >
            <CameraIcon className="w-4 h-4 mr-2" />
            Camera
          </Button>
          <Button size="sm" variant="outline">
            Logout
          </Button>
        </div>
      </header>
      <div className="flex-1 p-4 md:p-8 flex items-center justify-center">
        <div className="flex flex-col gap-4">
          <div className="grid gap-4 md:grid-cols-2">
            <div className="flex flex-col gap-2 items-center">
              <h1 className="text-3xl font-bold">Mood</h1>
              <p className="text-gray-500 grid gap-2 md:text-base/relaxed dark:text-gray-400">
                Upload an image to get personalized song suggestions based on
                your mood. Make sure your face is visible in the image.
              </p>
              <img
                alt="User Image"
                className="aspect-square rounded-lg object-cover overflow-hidden"
                height={400}
                src="/placeholder.svg"
                width={400}
              />
              <div className="flex items-center gap-4">
                <Button size="sm">
                  <UploadIcon className="w-4 h-4 mr-2" />
                  Upload Image
                </Button>
                <Button size="sm">
                  <CameraIcon className="w-4 h-4 mr-2" />
                  Take Photo
                </Button>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <h2 className="text-2xl font-bold">Top Songs</h2>
              <ul className="grid gap-4">
                <li className="flex items-center gap-4">
                  <img
                    alt="Song Image"
                    className="aspect-square rounded-lg object-cover overflow-hidden"
                    height={100}
                    src="/placeholder.svg"
                    width={100}
                  />
                  <div className="grid gap-1.5">
                    <h3 className="font-bold">Blinding Lights</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      The Weeknd
                    </p>
                  </div>
                </li>
                <li className="flex items-center gap-4">
                  <img
                    alt="Song Image"
                    className="aspect-square rounded-lg object-cover overflow-hidden"
                    height={100}
                    src="/placeholder.svg"
                    width={100}
                  />
                  <div className="grid gap-1.5">
                    <h3 className="font-bold">Blinding Lights</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      The Weeknd
                    </p>
                  </div>
                </li>
                <li className="flex items-center gap-4">
                  <img
                    alt="Song Image"
                    className="aspect-square rounded-lg object-cover overflow-hidden"
                    height={100}
                    src="/placeholder.svg"
                    width={100}
                  />
                  <div className="grid gap-1.5">
                    <h3 className="font-bold">Blinding Lights</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      The Weeknd
                    </p>
                  </div>
                </li>
                <li className="flex items-center gap-4">
                  <img
                    alt="Song Image"
                    className="aspect-square rounded-lg object-cover overflow-hidden"
                    height={100}
                    src="/placeholder.svg"
                    width={100}
                  />
                  <div className="grid gap-1.5">
                    <h3 className="font-bold">Blinding Lights</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      The Weeknd
                    </p>
                  </div>
                </li>
                <li className="flex items-center gap-4">
                  <img
                    alt="Song Image"
                    className="aspect-square rounded-lg object-cover overflow-hidden"
                    height={100}
                    src="/placeholder.svg"
                    width={100}
                  />
                  <div className="grid gap-1.5">
                    <h3 className="font-bold">Blinding Lights</h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      The Weeknd
                    </p>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function CameraIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
      <circle cx="12" cy="13" r="3" />
    </svg>
  );
}

function MusicIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 18V5l12-2v13" />
      <circle cx="6" cy="18" r="3" />
      <circle cx="18" cy="16" r="3" />
    </svg>
  );
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}
